### ISSUE TITLE
Add `:TSPlaygroundToggle`

### ISSUE THREAD

**Issue by vigoux** [nvim-treesitter/playground#1]
It would be great to be able to enable the plugin with a command.
Plus the default mapping overlaps with `gt` to swtich tabs 😉

**Comment by steelsojka** [comment]
I agree. I don't like adding default keymaps..... I just remap them anyways. What would be a good default keymapping for this?

**Comment by vigoux** [comment]
I don't really know if a keymap fits here actually... As you might just want to toggle this not that often.

**Comment by steelsojka** [comment]
Agreed. I'll remove it.

**Comment by steelsojka** [comment]
merged #2
