### ISSUE TITLE
nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text

### ISSUE THREAD

**Issue by jrop** [nvim-treesitter/playground#101]
I've been seeing this warning whenever I run a query for the first time from the query editor.

**Comment by theHamsta** [comment]
We want to move away from `nvim-treesitter.ts_utils.get_node_text` but `vim.treesitter.query.get_node_text` doesn't fully replace it yet in the context of this plugin. It would require either extension of the `vim.treesitter.query.get_node_text` or a bit of refactoring in our code

**Comment by clason** [comment]
What is missing from upstream?

**Comment by clason** [comment]
Also, the long-term goal is to add a query editor to Neovim itself (like we did with the playground and the `:TSHighlightCapture` function), at which point this plugin should in fact no longer be needed.

**Comment by theHamsta** [comment]
It was for the refactor module that had a problem with the new version that allocates the string as it would do the concat and split pattern over and over again. We wanted to add a mode that would not allocate the concatenated string and instead return the original lines.

**Comment by clason** [comment]
You can control whether the upstream function concatenates or not?

**Comment by theHamsta** [comment]
oh, I see. I was added. Great!
