### ISSUE TITLE
Please provide tag for old versions or make it compatible with neovim 0.7-0.8

### ISSUE THREAD

**Issue by wookayin** [nvim-treesitter/playground#123]
Since commit db54848 (#120), playground requires neovim 0.9 or higher (it depends on treesitter [90ead4ed](https://github.com/nvim-treesitter/nvim-treesitter/commit/90ead4ed) or higher). I think this is too high requirement version for neovim because there are some system that is still using neovim 0.7 or 0.8.

While I would suggest lower the minimum required neovim version of this plugin, it'd be a good idea to provide tags (like v0.7.0) for last compatible version like nvim-tresitter plugin.

**Comment by clason** [comment]
PRs restoring compatibility with 0.8 are welcome (that PR was not supposed to break on 0.8). But we cannot support older versions; it is just too much effort.

And the goal is to deprecate this plugin sooner rather than later. If someone wants to fork it and provide support for older versions, they are very welcome to do so.

**Comment by wookayin** [comment]
Can we at least maintain tags?

**Comment by clason** [comment]
Not planned, at least not retroactively, sorry. If somebody else has the time and interest in maintaining an LTS version of this plugin, they can do so. Our efforts are focused on improving the official core implementation

**Comment by wookayin** [comment]
Makes sense, thanks! I always appreciate your efforts on neovim core development (and this plugin too).

**Comment by clason** [comment]
(but I hope someone provides a fix to restore the 0.8 compatibility)

**Comment by dtomvan** [comment]
Wait, wasn't the entire point of the `nvim-treesitter.compat` module to add compatibility between both nvim 0.8 and 0.9? How does `nvim-treesitter`-latest depend on nvim 0.9? If it does then the point of the compat module would be defeated...

**Comment by clason** [comment]
Again, this was a mistake in the PR that slipped past review; a followup PR to fix this is welcome.
