### ISSUE TITLE
deprecate this repo?

### ISSUE THREAD

**Issue by justinmk** [nvim-treesitter/playground#126]
Since Nvim 0.9 includes `:InspectTree` and related functionality, this repo's readme should prominently mention that, and possibly even announce its deprecation?

**Comment by clason** [comment]
Not yet; we're still missing the live query editor, and this also ties in with the ongoing Nvim-treesitter 1.0 rewrite (which will break this repo completely, like other -- not deprecated -- plugins).

So this is part of a greater process, which I'm tracking.

**Comment by clason** [comment]
Now that we have `:PreviewQuery` in Neovim, I have added a deprecation notice and will archive the repo shortly.
