### ISSUE TITLE
Error when opening fzf :Buffers or :Files

### ISSUE THREAD

**Issue by AlanWarren** [nvim-treesitter/playground#19]
Hello, 

I've noticed when I browse files or buffers with fzf that I'm getting an error with nvim-treesitter-playground. 

```Error executing vim.schedule lua callback: ...d/playground/lua/nvim-treesitter-playground/internal.lua:47: attempt to index local 'root_lang_tree' (a nil value)```

I'm using the latest nvim nightly, with latest nvim-treesitter, playground and fzf.vim.  To reproduce you need to open a file and toggle the playground view. After closing the playground split, use :Buffers or :Files and the error will display. 

The error mentioned does not prevent :Buffers and :Files from working, but it does introduce about 2 seconds delay to a normally instant command. 

If there's anything else I can provide please let me know.

Thanks!

**Comment by steelsojka** [comment]
This should be fixed with #21. Once that gets merged let me know if there is anymore issues.

**Comment by AlanWarren** [comment]
> This should be fixed with #21. Once that gets merged let me know if there is anymore issues.

I patched my copy to test this out, and it does fix the issue.  I'll go ahead and close this.  Thanks!
