### ISSUE TITLE
[Question] How to use query editor?

### ISSUE THREAD

**Issue by MuhammedZakir** [nvim-treesitter/playground#23]
Can anyone tell me how to use query editor? I have entered a query in it, but nothing happens and I am confused about what to do next.

**Comment by stsewd** [comment]
@MuhammedZakir you need to capture your query/node `(node) @foo`, then putting your cursor over `@foo` will highlight all matches in your code buffer.

**Comment by MuhammedZakir** [comment]
Thanks @stsewd! :-)

**Comment by talbergs** [comment]
Seems not to work as described now.
```
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.3 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v15.11.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found.
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - php            ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
```
In query editor I put cursor over `foo` and nothing is highlighted.
```
(php_tag) @foo
```
nvim-treesitter/playground@d96cef521d22afd1a409449a890f20f50b436ee1
```
NVIM v0.5.0-dev+1221-g9b2d4ff62
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
---
Tested with `-u NORC`

**Comment by dlants** [comment]
I spent a bunch of time scratching my head about this too. It would be nice to add an example about how to do this!

**Comment by stsewd** [comment]
Addressing this in https://github.com/nvim-treesitter/playground/pull/44
