### ISSUE TITLE
Doesn't seem to be working for JS/JSX

### ISSUE THREAD

**Issue by ChristianChiarulli** [nvim-treesitter/playground#27]
![image](https://user-images.githubusercontent.com/29136904/110670229-2bd18f00-819b-11eb-9112-8d8bb9bbf4c5.png)

Just checked and it is working for python so I'm not sure what the issue is.

**Comment by steelsojka** [comment]
Can you provide a reproduceable scenario? Seems to be working fine for JS/JSX.
![Screen Shot 2021-03-23 at 6 59 27 AM](https://user-images.githubusercontent.com/2062154/112143075-65e05f00-8ba5-11eb-84ef-3bbf5fcab1f9.png)

**Comment by stsewd** [comment]
Hi, make sure you have the js/jsx parsers installed `TSInstall javascript`, let us know if you still have this problem or if you have a reproducible example.
