### ISSUE TITLE
Playground not working

### ISSUE THREAD

**Issue by darioisthebest** [nvim-treesitter/playground#30]
I have tried several languages, nvim-treesitter works but when I do :TSPlaygroundToggle the tree is always empty, for example, I have this javascript code:
```javascript
function Hello() {
    this.hello = () => console.log("Hello!");
    this.howdy = () => console.log("Howdy!");
}
```
the tree is empty (but with the code there is nothing wrong, when I try to run it works) so every time that I refresh the tree, there is always this error:
```
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/dario/.config/nv
im/plugged/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13 
```

I don't have any particular configuration for nvim-treesitter, I just followed the nvim-treesitter guide.

**Comment by steelsojka** [comment]
Update your neovim to the latest nightly and update nvim-treesitter to the latest. Then reinstall the parsers with `:TSUpdate`. There was a breaking change recently in tree-sitter that requires all parsers to be updated.

**Comment by darioisthebest** [comment]
I already have re-compiled neovim to the latest version and when I do `:TSUpdate` it says All parsers are up-to-date

**Comment by steelsojka** [comment]
Have you updated nvim-treesitter? Can you share the versions you are on for the plugins (nvim-treesitter and playground).

**Comment by darioisthebest** [comment]
tree-sitter version is tree-sitter 0.19.3 and I updated all the plugins right now so I have the latest version of nvim-treesitter and latest version of treesitter playground.

**Comment by steelsojka** [comment]
Can you share the versions that you have? Also, are you using tree-sitter bundled with neovim?

**Comment by darioisthebest** [comment]
If you tell me how to get the version i'm going to do that,
yes, I use tree-sitter bundled with neovim
and I installed neovim with `yay -S neovim-nightly`

**Comment by darioisthebest** [comment]
So I figured out that my neovim was 0.5+ but was not the latest version, so once I updated everything worked properly (if you are in arch `yay -S neovim-nightly-git` is wrong and outdated just use `yay -s neovim-git`).

**Comment by brycepg** [comment]
I had the issue of playground showing up blank until I switched from a manual install of `lua-language-server` to installing is via mason with `:LSPInstall lua-language server`. I also switched from fedora neovim to bob-nvim
