### ISSUE TITLE
Feature: Execute queries

### ISSUE THREAD

**Issue by leoluz** [nvim-treesitter/playground#39]
First of all, thank you for this super useful plugin!

It would be great if we could have the feature to open an additional (scratch) buffer at the bottom where we could write and execute queries on the opened file. I tried to find this feature implemented in different tools but couldn't find it anywhere.

**Comment by vigoux** [comment]
Hi, I think the feature you mean is already implemented, maybe have a look at what hitting the `q` key in the playground tree buffer ?

This should bring a new buffer allowing you to enter q auery that'll be exectued.

**Comment by leoluz** [comment]
Ah nice! It's right there in the README 😓 
```
- `R`: Refreshes the playground view when focused or reloads the query when the query editor is focused.
- `o`: Toggles the query editor when the playground is focused.
```
