### ISSUE TITLE
Folder permissions for .cache directory not created correctly

### ISSUE THREAD

**Issue by steelsojka** [nvim-treesitter/playground#4]
I'm not sure how the permissions work with `libuv`. Need to figure this one out.

**Comment by tjdevries** [comment]
https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/lib/fs.lua Might be useful.

**Comment by steelsojka** [comment]
Fixed in #5. Originally I had 755 but I must be thinking it's the same as a `chmod`, which doesn't seem to be the case.

**Comment by steelsojka** [comment]
@tjdevries Thanks for pointing me in the right direction.
