### ISSUE TITLE
Keybind for Query editor not working

### ISSUE THREAD

**Issue by dskleingeld** [nvim-treesitter/playground#52]
When pressing `o` while in the playground buffer the query editor will not open. If I run the command 
```lua
:lua require "nvim-treesitter-playground.internal".toggle_query_editor(0)
```
it does open. I made sure 
- the tree-sitter setup runs as last item in my config. 
- the treesitter parsers are installed and up to date
- I use the exact setup as in the README
- the language was supported by treesitter playground (I used rust)

What else can I do to troubleshoot?

This is on NVIM v0.5.0 with the current master branch of treesitter playground

**Comment by stsewd** [comment]
Hi, are you calling the setup function in your config as the shown on https://github.com/nvim-treesitter/playground#setup?

**Comment by dskleingeld** [comment]
I copied the setup function directly from the readme. See the relevant functions in my config here:

- [init.lua](https://github.com/dskleingeld/new-linux-setup/blob/master/vim/init.lua) includes `plugins.lua` and `treesitter.lua`
- [plugins.lua](https://github.com/dskleingeld/new-linux-setup/blob/f42ef540386c92c2248a38c8d36212030abdab4e/vim/lua/plugins.lua#L57) installs playground using packer
- [treesitter.lua](https://github.com/dskleingeld/new-linux-setup/blob/f42ef540386c92c2248a38c8d36212030abdab4e/vim/lua/treesitter.lua#L25) sets up treesitter plugins including playground

**Comment by stsewd** [comment]
@dskleingeld can you check on the playground buffer this? `:verbose map o`

BTW, If you don't want to change the defaults, you can just add ` playground = {enable = true}`

**Comment by dskleingeld** [comment]
The output was: 
```
n  o            @:lua require "nvim-treesitter-playground.internal".toggle_query_editor(1)<CR>
        Last set from ~/.local/share/nvim/site/pack/packer/start/playground/plugin/nvim-treesitter-playground.vim
```

Or see the screenshot:
![image](https://user-images.githubusercontent.com/11743287/128641111-bb369775-e61b-4378-86d0-40192f92d1aa.png)

**Comment by stsewd** [comment]
so, the query editor just doesn't show up or do you see any errors?

**Comment by dskleingeld** [comment]
It doesn't show up, I do not see any errors. I click with my mouse in the playground window and press 'o'. Then nothing happens.

**Comment by stsewd** [comment]
Does executing the same command from `:map o` works? this is `:lua require "nvim-treesitter-playground.internal".toggle_query_editor(1)` for the example you showed.

Also, try replicating this with a minimal init.vim, maybe another plugin is breaking this.

**Comment by dskleingeld** [comment]
Okay..... so I went through my config disabling everything except this plugin and it worked! So then I started re-enabling my config bit by bit and found the cause.... It is the second of these two lines:
```lua
map('n', ';', ':', options)
map('n', ':', ';', options)
```
The map from `:` to `;` in normal mode _somehow_ blocks the query editor from opening when pressing `o`. 🤔🥴

Opening the query window using the command works btw.

**Comment by waldson** [comment]
I have the same problem. The issue is that mapping are being set as recursive on: 
https://github.com/nvim-treesitter/playground/blob/master/lua/nvim-treesitter-playground/internal.lua#L215

To fix it, I just changed this line from:
```lua
{ silent = true }
```

to:
```lua
{ silent = true, noremap = true }
```
