### ISSUE TITLE
Error executing vim.schedule lua callback: internal.lua:514: table index is nil

### ISSUE THREAD

**Issue by glyh** [nvim-treesitter/playground#53]
Step to reproduce: 
1. open neovim 
2. set filetype lua 
3. write `x[]`
4. Open Treesitter playground, open query window, type `(expression)@expr`
5. move cursor on expr
6. move back to `x[]`
7. open a new line under it with `o`

![image](https://user-images.githubusercontent.com/12870742/128353134-c89c2beb-3598-4f64-b9ad-08aecf2b3dcb.png)

**Comment by clason** [comment]
I cannot reproduce this at the moment. Could you test with the latest versions of nvim-treesitter and playground (we switched the Lua parser in the meantime)?

**Comment by stsewd** [comment]
I was able to reproduce this, this should fix it https://github.com/nvim-treesitter/playground/pull/73.
