### ISSUE TITLE
Unable to start playground

### ISSUE THREAD

**Issue by meain** [nvim-treesitter/playground#6]
When I run `TSPlaygroundToggle`, I get the following error.

```
Error executing vim.schedule lua callback: ...d/playground/lua/nvim-treesitter-playground/internal.lua:231: attempt to index local 'lnums' (a nil value)
```

https://github.com/nvim-treesitter/playground/blob/ccf1f62466a12670fa82e140acad3ef6550b69e2/lua/nvim-treesitter-playground/internal.lua#L189 the value of `results` here is nil.

### Config:

Right out of the readme.

```
  playground = {
    enable = true,
    disable = {},
    updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
    persist_queries = false -- Whether the query persists across vim sessions
  }
```

---
Neovim version: `NVIM v0.5.0-8c49e3d50`

**Comment by vigoux** [comment]
Hi, thanks for reporting !

Do you have the parser installed for the buffer you are trying the run the playground on ?

**Comment by meain** [comment]
Yup. In any case I had `all` as the install candidate. Checked with both `lua` and `python`. Same error.

**Comment by steelsojka** [comment]
Can you give an example file and steps to reproduce?

**Comment by meain** [comment]
I stripped down the config to just:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'nvim-treesitter/playground'
call plug#end()


lua <<EOF
require'nvim-treesitter.configs'.setup {
  playground = {
    enable = true,
    disable = {},
    updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
    persist_queries = false -- Whether the query persists across vim sessions
  }
}
EOF
```

But still getting an error.

**Comment by meain** [comment]
Oh, wait. My bad. It works after I updated to current master.
