### ISSUE TITLE
`:TSHighlightCapturesUnderCursor` no longer displays language specific info after update

### ISSUE THREAD

**Issue by lmburns** [nvim-treesitter/playground#60]
I've had the configuration for `playground` and `nvim-treesitter` for quite a while (since October) and haven't messed with it until now. I just updated to the latest version of `nvim-treesiter`. I had to delete the folder manually because `vim-plug` wouldn't  update it due to modified files. 

After I did this, when running `:TSHighlightCapturesUnderCursor`, the language specific highlight groups are no longer displayed. For example:

`pub(crate)...` in Rust, when running that command on `pub` only this is displayed:
```
# Treesitter
* **@keyword** -> 1965 -> **TSKeyword**
```

There used to be something that would say `rustTS...`.

This could be something that I am doing wrong that I forgot to do this time around after installing, or something that I didn't see in the recommendation for the configuration. If that is the case, I am sorry, otherwise, this may have something to do with an update. Here is my configuration:
```lua
require('nvim-treesitter.configs').setup {
  ensure_installed = {
    "c", "cpp", "go", "gomod", "rust", "python", "java", "query"
  },
  sync_install = false,
  ignore_install = {}, -- List of parsers to ignore installing
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = {}, -- list of language that will be disabled
    additional_vim_regex_highlighting = false
  },
  playground = {
    enable = true,
    disable = {},
    updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
    persist_queries = false, -- Whether the query persists across vim sessions
    keybindings = {
      toggle_query_editor = 'o',
      toggle_hl_groups = 'i',
      toggle_injected_languages = 't',
      toggle_anonymous_nodes = 'a',
      toggle_language_display = 'I',
      focus_language = 'f',
      unfocus_language = 'F',
      update = 'R',
      goto_node = '<cr>',
      show_help = '?'
    }
  }
}
```

**Comment by stsewd** [comment]
Thanks for reporting! This should fix it https://github.com/nvim-treesitter/playground/pull/61

**Comment by lmburns** [comment]
Yes this does work. Sorry for the later reply. I think that this can be merged and I'll close the issue
