### ISSUE TITLE
TSHighlightCapturesUnderCursor gives numbers instead of groups

### ISSUE THREAD

**Issue by haze** [nvim-treesitter/playground#65]
When running `TSHighlightCapturesUnderCursor` I'm met with intermediary groups that are represented as numbers instead of their captures (like shown in the image in the README). An example is shown below:

<img width="579" alt="CleanShot 2022-02-09 at 23 13 21@2x" src="https://user-images.githubusercontent.com/15584994/153335880-8e22c490-f149-427b-984f-68e485cfabb7.png">

Is there something wrong in my configuration? I can provide it if this isn't a common issue and my searching just sucks

**Comment by theHamsta** [comment]
No, this is expected and was changed as an optimization in core. We should update the playground module and do a reverse lookup of that number again

**Comment by haze** [comment]
Had I looked harder I could’ve noticed that #61 solves this. I’ll close this issue when that or another fix is merged
