### ISSUE TITLE
`TSHighlightCapturesUnderCursor` is a mouthful

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/playground#68]
Maybe we can add a short alias like `:TSCaptures`?

**Comment by stsewd** [comment]
I usually just do `:tsh<tab>`

**Comment by clason** [comment]
That's a good suggestion, but I find myself having to type it in chat too often as well ;)

**Comment by clason** [comment]
Just realized that `:TSH` will work, too (as long as you don't have defined your own `:TSHappy` command).
