### ISSUE TITLE
Two-way sync between playground and buffer

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/playground#69]
Currently, moving through the playground highlights the corresponding text in the parsed buffer. It would be useful to (optionally) have this work the other way around: when moving through the buffer, highlight the (either largest or smallest, doesn't really matter) capture in the playground corresponding to what's under the cursor.

**Comment by fisher-j** [comment]
I think that what you describe is supposed to be how it works. Unfortunately, this is not working for me either.

**Comment by DasGandlaf** [comment]
Not working for me neither :/

**Comment by ViRu-ThE-ViRuS** [comment]
this works for `vim.treesitter.inspect_tree()` / `:InspectTree` on `neovim 0.9`. 
I cant see why it cant be made to work for `playground` in 0.9 atleast.

**Comment by clason** [comment]
Because there's no reason to spend the limited developer time fixing `playground` when a better alternative already exists in Neovim core. The goal is to upstream everything from playground and deprecate this plugin.
