### ISSUE TITLE
Add actual highlight information to `TSHighlightCapturesUnderCursor`

### ISSUE THREAD

**Issue by wimstefan** [nvim-treesitter/playground#70]
It would be an helpful addition to include the information provided by the `highlight` command besides `Treesitter` and `Syntax` if possible.
I get that currently with an extra function but perhaps it would be possible to integrate that in the `TSHighlightCapturesUnderCursor` popup?

Since I'm never sure whether I use the correct words and terms I've created a picture to clarify what I mean:
![treesitter-expanded](https://user-images.githubusercontent.com/4605934/156925409-e0163618-b5ab-4657-a07e-6db75e57327d.png)

**Comment by lf-** [comment]
What's that extra function called? I have tried my old vimscript trick and it doesn't work:

```vim
" Get the highlight groups under the cursor
function! s:syntax_query() abort
  for id in synstack(line("."), col("."))
    echo synIDattr(id, "name")
  endfor
endfunction
command! SyntaxQuery call <SID>syntax_query()
```

**Comment by theHamsta** [comment]
You can now use `:Inspect` in nightly
