### ISSUE TITLE
Add :TSNodeUnderCursor

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/playground#72]
Sometimes you don't want to see the full tree, but only get the node(s) for whatever is under your cursor. Opening the playground and scrolling through it to find your place can be tedious (since there's no locked view).

Would be nice to have a command analogous to `:TSHighlightCapturesUnderCursor` that pops up a float with that information, either as the leaf node, or as a full path from the root.

**Comment by aspeddro** [comment]
@clason, I was playing around with the tree sitter and implemented this feature. There are some details that I don't quite understand. I can open a PR if you wish.


https://user-images.githubusercontent.com/16160544/161361479-c939ab0c-2d7a-4880-acb5-027fffc71a7a.mp4

**Comment by clason** [comment]
Sure, please do!
