### ISSUE TITLE
Catching nodes from a custom module

### ISSUE THREAD

**Issue by ribelo** [nvim-treesitter/playground#80]
Unfortunately I cannot find the information anywhere, so let me ask you.

Is it possible to use `playground` to write a custom module for treesitter? To make it easier, let's say I would like to add a language for `treesitter-textobjects`, can I use playground for that?

**Comment by theHamsta** [comment]
Yes, you can use the playground for any parser (if you refer to that as "module"). You can find information in the README of nvim-treesitter on how to add parsers. You can just specify a local path.

You can also use the playground to test nvim-treesitter Lua modules. But the playground is mostly thought to test queries for that module.
