### ISSUE TITLE
How to use it to find highlight groups for cmp completion window (and documentation)?

### ISSUE THREAD

**Issue by hrqmonteiro** [nvim-treesitter/playground#84]
I have a problem in my colorscheme, as you can see, when i use `cmp`, the documentation has this highlight groups that are not consistent with the color of the completion window, and i need to find the highlight groups for it.
It came to me the suggestion of this tree-sitter playground.

![Screenshot from 2022-07-03 22-39-50](https://user-images.githubusercontent.com/17055027/177142723-66a081d3-d979-43c4-8421-c5e9fec70a44.png)

But i still wasn´t able to use it properly. If i use the `TSHighlightCapturesUnderCursor`, it gives me the highlight for the thing i am writing, and i am not able to get to the cmp window, like, i was writing and used it:

![Screenshot from 2022-07-04 08-09-30](https://user-images.githubusercontent.com/17055027/177143079-4a58d77b-6fb1-4094-9883-7048a69e9926.png)

It gave me `tsxTSVariable`, which is not all all what i am trying to get...

How can i find the groups for the `cmp` window and documentation?

**Comment by clason** [comment]
Is `nvim-cmp` even using treesitter for its float? I think it's easier to check the `nvim-cmp` sources (or ask at the repo) for the highlight groups it uses.
