### ISSUE TITLE
Full name of highlight group not displayed by TSHighlightCaptureUnderCursor

### ISSUE THREAD

**Issue by anthony-S93** [nvim-treesitter/playground#94]
This is a bit similar to #70, but I still can't get the full name of the highlight group to show with `TSHighlightCaptureUnderCursor` as shown in the README. 
![image](https://user-images.githubusercontent.com/69449791/188524005-33bf68a9-2a0c-49c0-b74b-1f23002fbecf.png)

Here is mine: 
![Screenshot_2022-09-06_08-32-52](https://user-images.githubusercontent.com/69449791/188524042-ea10e7dd-0156-4856-a7d1-5f98130a7870.jpg)

For some reason, the full name of the highlight group wasn't displayed. I'm obviously missing something here. 

My configs:

```lua
        use
	{
	    "nvim-treesitter/nvim-treesitter",
	    run = ':TSUpdate',
	    config = function()
		require("nvim-treesitter.configs").setup{
		    highlight = {
				enable = true,
				additional_vim_regex_highlighting = true,
		    },
		    ensure_installed = {"c", "cpp", "java", "python", "lua"},
		}
	    end,
	}

	use
	{
	    "nvim-treesitter/playground",
	    config = function()
		playgrond = {
		    enable = true,
		    disable = {},
		    updatetime = 25,
		    persist_queries = false,
		    keybindings = {
				toggle_query_editor = 'o',
				toggle_hl_groupd = 'i',
				toggle_injected_languages = 't',
				toggle_anonymous_nodes = 'a',
				toggle_language_display = 'I',
				focus_language = 'f',
				unfocus_language = 'F',
				update = 'R',
				goto_node = '<cr>',
				show_help = '?',
		    },
		}
	    end,
        --after = {"nvim-treesitter"}
	}
```

**Comment by clason** [comment]
Those _are_ the full names of the highlight groups after a recent change to Neovim. The function has to be adapted to again show the linked highlight groups (if any).

**Comment by gsheru** [comment]
Same here.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/3118869/190923853-5f8cae0a-7eb5-488c-828c-72685fc125eb.png">

Capture group is shown but higroups do not.

**Comment by clason** [comment]
Capture group _is_ highlight group for 0.8.

**Comment by gsheru** [comment]
> Capture group _is_ highlight group for 0.8.

With the `@` and the dots? Like in `@function.builtin`?
And we loose the syntax prefix? Like in `vimTSConstant`?

There is any documentation about that change? To be prepared. And to learn the reason and benefits behind than change.
That'll be a huge pain in the bumbum for a lot of colorschemes, I think. But... 🤷

**Comment by clason** [comment]
Closing this as basically "won't fix", since the capture name (plus implicit `.language`) now replaces the chain of highlight links.

Showing custom links was never part of this functionality but is already tracked as a new feature request in #70.
