### ISSUE TITLE
`TSHighlightCapturesUnderCursor` no longer shows highlight groups

### ISSUE THREAD

**Issue by bartels** [nvim-treesitter/playground#97]
`TSHighlightCapturesUnderCursor` is not showing the highlight groups anymore

The problem appears to have start for me with pull request #87. If I check out the commit previous to that, things work again.

![playground_highlights](https://user-images.githubusercontent.com/471642/193334635-4e88987f-94e3-439b-9305-718cae4fe46b.png)  

The image shows the correct output (bottom half) and incorrect (top half - after including #87 )

**Comment by clason** [comment]
`@keyword` _is_ the highlight group on Neovim 0.8.

**Comment by bartels** [comment]
Ok, I guess I meant the linked highlight groups, but maybe that's not exactly what it was showing previously

It looks like #70 covers it
